-- KHỞI TẠO LAB03


USE LAB02

-- KHỞI TẠO BẢNG (VATTU)
CREATE TABLE VATTU
(
	MAVTU CHAR(4) NOT NULL CONSTRAINT PK_MAVTU PRIMARY KEY
	,TENVTU VARCHAR(100) NOT NULL UNIQUE
	,DVTINH VARCHAR(10) NULL CONSTRAINT DF_VATTU_DVITINH DEFAULT ''
	,PHANTRAM REAL CONSTRAINT CK_VATTU_PHANTRAM CHECK(0<=PHANTRAM AND PHANTRAM<=100)
)
GO
--KHỞI TẠO BẢNG (NHACC)
CREATE TABLE NHACC
(
	MANHACC CHAR(3) NOT NULL CONSTRAINT PK_MANHACC PRIMARY KEY
	,TENNHACC VARCHAR(100) NOT NULL UNIQUE
	,DIACHI VARCHAR(200) NOT NULL UNIQUE
	,DIENTHOAI VARCHAR(20) NOT NULL CONSTRAINT DF_NHACC_DIENTHOAI DEFAULT N'CHƯA CÓ'
)
GO
-- KHỞI TẠO BẢNG (DONDH)
CREATE TABLE DONDH
(
	SODH CHAR(4) NOT NULL CONSTRAINT PK_SONDH PRIMARY KEY
	,NGAYDH DATETIME CONSTRAINT DF_DONDH_NGAYDH DEFAULT GETDATE()
	,MANHACC CHAR(3) NOT NULL
)
GO
-- KHỞI TẠO BẢNG (CTDONDH)
CREATE TABLE CTDONDH
(
	SODH CHAR(4) NOT NULL CONSTRAINT FK_CTDONDH_SODH_SODH FOREIGN KEY REFERENCES DONDH
	,MAVTU CHAR(4) NOT NULL CONSTRAINT FK_CTDONTDH_MAVTU_MAVTU FOREIGN KEY REFERENCES VATTU
	,SLDAT INT NOT NULL CONSTRAINT CK_CTDONTDH_SLDAT CHECK(SLDAT>0)
)
GO
-- KHỞI TẠO BẢNG (PNHAP)
CREATE TABLE PNHAP
(
	SOPN CHAR(4) CONSTRAINT PK_SOPN PRIMARY KEY
	,NGAYNHAP DATETIME CONSTRAINT DF_PNHAP_NGAYNHAP DEFAULT GETDATE()
	,SODH CHAR(4) NOT NULL CONSTRAINT FK_PNHAP_SOPN_SODH FOREIGN KEY REFERENCES DONDH
)
GO
-- KHỞI TẠO BẢNG(CTPNHAP)
CREATE TABLE CTPNHAP
(
	SOPN CHAR(4) NOT NULL
	,MAVTU CHAR(4) NOT NULL CONSTRAINT FK_CTPNHAP_MAVTU_MAVTU FOREIGN KEY REFERENCES VATTU
	,SLNHAP INT NOT NULL CONSTRAINT CK_CTPNHAP_SLNHAP CHECK(SLNHAP>0)
)
GO
-- KHỞI TẠO BẢNG (CTPXUAT)
CREATE TABLE CTPXUAT
(
	SOPX CHAR(4) NOT NULL 
	,MAVTU CHAR(4) NOT NULL CONSTRAINT FK_CTPXUAT_MAVTU_MAVTU FOREIGN KEY REFERENCES VATTU
	,SLXUAT INT NOT NULL CONSTRAINT CK_CTPXUAT_SLXUAT CHECK (SLXUAT>0)
	,DGXUAT MONEY NOT NULL CONSTRAINT CK_CTPXUAT_DGXUAT CHECK (DGXUAT>0)
	,CONSTRAINT PK_CTPXUAT PRIMARY KEY (SOPX,MAVTU)
)
GO
-- KHỞI TẠO BẢNG (TONKHO)
CREATE TABLE TONKHO
(
	NAMTHANG CHAR(6) NOT NULL
	,MAVTU CHAR(4) CONSTRAINT FK_TONKHO_MAVTU_MAVTU FOREIGN KEY REFERENCES VATTU
	,SLDAU INT	NOT NULL CONSTRAINT CK_TONKHO_SLDAU CHECK(SLDAU>0)
	,TONGSLN INT NOT NULL CONSTRAINT CK_TONKHO_TONGSLN CHECK (TONGSLN>0)
	,TONGSLX INT NOT NULL CONSTRAINT CK_TONKHO_TONGSLX CHECK (TONGSLX>0)
	,SLCUOI AS (SLDAU + TONGSLN - TONGSLX) PERSISTED
	,CONSTRAINT PK_TONKHO PRIMARY KEY (NAMTHANG,MAVTU)
)
GO