
-- Truy v?n con
-- Truy v?n tham chi?u
-- LESSON05-TRUY V?N D? LI?U NÂNG CAO
--12 Truy v?n g?p
-- GROUP BY <DS C?T KHÔNG N?M TRONG B?U TH?C TH?NG KÊ>

USE DEV2311LM_SQL_04
SELECT *FROM SinhVien ORDER BY MaKH
GO
-- Th?c hi?n tính toàn g?p  nhóm theo tiêu chí nào ?ó ,thông th??ng có s? d?ng các hàm th?ng kê
-- SUM , COUNT , MAX , MIN , AVG

-- LI?T KÊ CÁC THÔNG TIN : MÃ KHOA ,T?NG H?C B?NG C?A T?NG KHOA

SELECT MaKH ,ISNULL(SUM(HOCBONG),0) AS [T?NG H?C B?NG]
FROM SinhVien
GROUP BY MaKH
GO
-- TÍNH T?NG H?C B?NG THEO T?NG KHOA THÔNG TIN G?M CÓ : MAKH,TENKH,T?NG H?C B?NG
SELECT K.MaKH ,ISNULL(SUM(HOCBONG),0) AS [T?NG H?C B?NG],TenKH
FROM SinhVien AS S
	 RIGHT JOIN KHOA AS K ON S.MAKH =K.MaKH
GROUP BY K.MaKH,TenKH
GO
-- Tính ?i?m trung bình c?a t?ng sinh viên thông tin g?m :MASV ,hosv,tensv,phai,diemtb
SELECT S.MASV,HOSV,TENSV,Phai,ROUND(ISNULL(AVG(DIEM),0),2) AS [DI?M TB]
FROM SinhVien AS S
		 LEFT JOIN KETQUA AS K ON S.MaSV = K.MaSV
GROUP BY  S.MaSV,HOSV,TENSV,Phai
GO
-- Th?ng kê ?i?m thi cao nh?t theo t?ng môn h?c,thông tin g?m :mamh,tenmh,Sotiet,Diem cao nhat
--max
--min
SELECT M.MaMH ,TenMH SOTIET, MAX(DIEM)as MAXDIEM,MIN(DIEM) as MINDIEM
FROM MONHOC AS M
		FULL JOIN Ketqua AS K ON M.MaMH=K.MaMH
	GROUP BY M.MaMH,TenMH,Sotiet
-- 13.TRUY V?N G?P NHÓM CÓ ?I?U KI?N
--HAVING BI?U TH?C ?I?U KI?N CÓ CH?A HÀM TH?NG KÊ
-- TH?NG KÊ NH?NG SINH VIÊN CÓ ?I?M TRUNG BÌNH >=5 AVG(DIEM)>=5
SELECT S.MASV,HOSV,TENSV,Phai,ROUND(ISNULL(AVG(DIEM),0),2) AS [DI?M TB]
FROM SinhVien AS S
		  JOIN KETQUA AS K ON S.MaSV = K.MaSV
GROUP BY  S.MaSV,HOSV,TENSV,Phai
HAVING AVG(DIEM) >=5
-- TH?NG KÊ NH?NG SINH VIÊN CÓ ?I?M TRUNG BÌNH >=5 AVG(DIEM)>=5 VÀ KHONG CO MON NAO DUOI 5
SELECT S.MASV,HOSV,TENSV,Phai,ROUND(ISNULL(AVG(DIEM),0),2) AS [DI?M TB]
FROM SinhVien AS S
		  JOIN KETQUA AS K ON S.MaSV = K.MaSV
GROUP BY  S.MaSV,HOSV,TENSV,Phai
HAVING AVG(DIEM) >=5 AND  MIN(Diem)>=5
GO
-- TH?NG KÊ NH?NG SINH VIÊN CÓ ?I?M TRUNG BÌNH <5 AVG
SELECT S.MASV,HOSV,TENSV,Phai,ROUND(ISNULL(AVG(DIEM),0),2) AS [DI?M TB]
FROM SinhVien AS S
		LEFT  JOIN KETQUA AS K ON S.MaSV = K.MaSV
GROUP BY  S.MaSV,HOSV,TENSV,Phai
HAVING ISNULL(AVG(DIEM),0) < 5
GO
--14 TRUY V?N CON
-- LO?I TRUY V?N CÓ CH?A M?T CÂU L?NH TRUY V?N KHÁC ??T TRONG SELECT , FROM , WHERE ,HAVING
-- LI?T KÊ CÁC KHOA CH?A CÓ SINH VIÊN H?C
SELECT * FROM Khoa
WHERE MaKH NOT IN (SELECT DISTINCT MaKH FROM SinhVien WHERE MaKH IS NOT NULL)

-- LI?T KÊ CÁC SINH VIÊN CH?A THI MÔN TRÍ TU? NHÂN T?O
SELECT * FROM SinhVien AS S
WHERE S.MaSV NOT IN (SELECT MaSV FROM Ketqua WHERE MaMH='02')
SELECT * FROM SinhVien AS S
WHERE S.MaSV NOT IN (SELECT MaSV FROM Ketqua AS K ,MonHoc AS M 
						WHERE K.MaMH=M.MaMH AND TenMH = N'Trí Tu? Nhân T?o')
--15 CÂU L?NH TRUY V?N THAM CHI?U
-- Câu l?nh truy v?n con,có ?i?u ki?n tam chi?u ??n truy v?n cha
-- Li?t kê thông tin :makh, tenkh,tongsv,tongnam,tongnu

SELECT MAKH,TENKH,TONGNAM = (SELECT COUNT(MASV) FROM SinhVien WHERE MAKH =K.MAKH)
				,TONGNAM =(SELECT COUNT(MASV) FROM SinhVien WHERE MAKH =K.MAKH AND Phai =1)
				,TONGNU =(SELECT COUNT(MASV) FROM SinhVien WHERE MAKH =K.MAKH AND Phai =0)
FROM KHOA AS K
-- CÁCH KHÁC
SELECT K.MAKH,TenKH,TONGSV = COUNT(MASV) ,SUM(IIF(PHAI=1,1,0)) AS TONGNAM,SUM(IIF(PHAI=1,0,1)) AS TONGNU
FROM KHOA AS K
	LEFT JOIN SinhVien AS S ON K.MaKH=S.MaKH
GROUP BY K.MaKH,TenKH
GO
--16 TRUY V?N T?O B?NG (MAKE TABLE QUERY)
-- INTO : S? D?NG TRONG TRUY V?N 
SELECT *
INTO SINHVIEN_TEMP
FROM SinhVien 
GO
-- B?NG T?M
-- #TABLE
SELECT K.MAKH,TenKH,TONGSV = COUNT(MASV) ,SUM(IIF(PHAI=1,1,0)) AS TONGNAM,SUM(IIF(PHAI=1,0,1)) AS TONGNU
INTO #THONGKEKHOA
FROM KHOA AS K
	LEFT JOIN SinhVien AS S ON K.MaKH=S.MaKH
GROUP BY K.MaKH,TenKH
GO


-- ##TABLE
SELECT K.MAKH,TenKH,TONGSV = COUNT(MASV) ,SUM(IIF(PHAI=1,1,0)) AS TONGNAM,SUM(IIF(PHAI=1,0,1)) AS TONGNU
INTO ##THONGKEKHOA
FROM KHOA AS K
	LEFT JOIN SinhVien AS S ON K.MaKH=S.MaKH
GROUP BY K.MaKH,TenKH
GO


--  17 THAM S?
DECLARE @NAME NVARCHAR(100)
SET @NAME ='AV'
SELECT * FROM KHOA WHERE MAKH = @NAME
GO
----==============----
---THÔNG KÊ D? LI?U

-- CHO BI?T  TRUNG BÌNH ?I?M THI THEO T?NG MÔN , G?M CÁC THÔNG TIN : MAMH,TENMH,TRUNGBINH DIEM
SELECT K.MaMH,TenMH,AVG(DIEM) AS [DI?M TB]
FROM Ketqua AS K
		  JOIN MonHoc AS M ON M.MaMH = K.MaMH
GROUP BY  K.MaMH,TenMH

-- DANH SÁCH S? MÔN THI C?A T?NG SINH VIÊN G?M HOTEN SV,TENKH, TONGSOMON
SELECT S.MASV,HOSV,TENSV, COUNT(MaMH) AS TONGSOMON
FROM SinhVien AS S
				JOIN Khoa AS K ON K.MaKH=S.MaKH
				JOIN Ketqua AS Q ON Q.MaSV=S.MaSV
GROUP BY S.MaSV,HOSV,TENSV

-- T?NG ?I?M THI C?A T?NG SINH VIÊN
SELECT S.MASV,HOSV,TENSV, SUM(DIEM) AS TONGDIEM
FROM SINHVIEN AS S
				JOIN Khoa AS K ON K.MaKH=S.MaKH
				JOIN KETQUA AS KQ ON KQ.MaSV=S.MaSV
GROUP BY S.MASV,HOSV,TENSV
-- T?NG S? SINH VIÊN ? CÁC KHOA
SELECT COUNT(S.MASV) AS TONGSV,K.MaKH
FROM SinhVien AS S
		  JOIN Khoa AS K ON K.MaKH = S.MaKH
GROUP BY  K.MaKH
-- CHO BI?T ?I?M CAO NH?T C?A M?I SINH VIÊN , G?M THÔNG TIN HO TEN SV, ?I?M'
SELECT S.TenSV, MAX(K.DIEM) AS [DIEM CAO NHAT ]
FROM SINHVIEN AS S
				JOIN Ketqua AS K ON S.MaSV=K.MaSV
GROUP BY S.TenSV
-- THÔNG TIN MÔN H?C CÓ NHI?U TI?T NH?T : TÊN MÔN HOC, SOTIET
SELECT TOP 1 TENMH, SOTIET
FROM MonHoc 
ORDER BY Sotiet DESC

USE DEV2311LM_SQL_04
-- CHO BI?T H?C B?NG CAO NH?T C?A T?NG KHOA G?M MÃ KHOA TÊN KHOA , H?C B?NG CAO NH?T
	SELECT	S.MaKH ,MAX(S.HOCBONG) AS [H?C B?NG CAO NH?T], K.TenKH
	 FROM SinhVien AS S
				JOIN KHOA AS K ON K.MaKH = S.MaKH
	GROUP BY S.MaKH,K.TenKH
-- CHO BI?T ?I?M CAO NH?T C?A M?I MÔN G?M : TÊN MÔN ,?I?M CAO NH?T
	SELECT M.TenMH,MAX(K.DIEM) AS [ ?I?M CAO NH?T]
		FROM MonHoc AS M 
			JOIN KETQUA AS K ON K.MAMH=M.MAMH
		GROUP BY M.TenMH
-- TH?NG KÊ S? SINH VIÊN H?C C?A T?NG MÔN : MÃ MÔN , TÊN MÔN , S? SINH VIÊN ?ANG H?C

	SELECT M.MaMH,M.TenMH,COUNT(S.MaSV)AS [ S? SINH VIÊN ?ANG H?C]
	FROM SinhVien AS S
			JOIN Ketqua AS K ON K.MaSV=S.MaSV
			JOIN MonHoc AS M ON M.MaMH =K.MaMH
	GROUP BY M.MaMH,M.TenMH

-- CHO BI?T TÊN MÔN NÀO CÓ ?I?M THI CAO NH?T G?M : TÊN MON , S? TI?T , TÊN SINH SV,?I?M ( C?N H?I )
	SELECT TOP(1)  MAX(K.DIEM) AS [?I?M CAO NH?T],S.MaSV,TenSV,M.TenMH,M.Sotiet
		FROM SinhVien AS S
			JOIN Ketqua AS K ON K.MaSV=S.MaSV
			JOIN MonHoc AS M ON M.MaMH = K.MaMH
	GROUP BY S.MaSV,TenSV,M.TenMH,M.Sotiet
	ORDER BY MAX(K.DIEM) DESC
-- CHO BI?T KHOA NÀO CÓ ?ÔNG SINH VIÊN NH?T G?M MÃ KHOA , TÊN KHOA , T?NG S? SINH VIÊN
	SELECT TOP(1) M.MaMH,M.TenMH,COUNT(S.MaSV)AS [ S? SINH VIÊN ?ANG H?C]
	FROM SinhVien AS S
			JOIN Ketqua AS K ON K.MaSV=S.MaSV
			JOIN MonHoc AS M ON M.MaMH =K.MaMH
	GROUP BY M.MaMH,M.TenMH
	ORDER BY COUNT(S.MaSV) DESC
-- CHO BI?T KHOA NÀO CÓ SINH VIÊN LÃNH H?C B?NG CAO NH?T G?M THÔNG TIN TÊN KHOA, H? TÊN SINH VIÊN , H?C B?NG
	SELECT TOP(1)K.TenKH, S.TENSV ,MAX(S.HOCBONG) AS [H?C BONG CAO NHAT]
		FROM SinhVien AS S
			JOIN Khoa AS K ON K.MaKH=S.MaKH
		GROUP BY K.TenKH, S.TENSV 
		ORDER BY MAX(S.HocBong) DESC
-- CHO BI?T SINH VIÊN C?A KHOA TIN H?C CÓ H?C B?NG CAO NH?T G?M CÁC THÔNG TIN : MASV,HOTEN SV,TENSV,TENKHOA,HOCBONG
	SELECT TOP(1)K.TenKH, S.HoSV, S.TENSV ,K.TenKH,HocBong
		FROM SinhVien AS S
			JOIN Khoa AS K ON K.MaKH=S.MaKH
		GROUP BY K.TenKH, S.HoSV, S.TENSV ,TenKH,HocBong
		HAVING TenKH LIKE N'Tin H?c'
-- CHO BI?T SINH VIÊN NÀO CÓ ?I?M MÔN C? S? D? LI?U L?N NH?T, G?M H? TÊN SV , TÊN MÔN , ?I?M
	SELECT TOP(1) S.HoSV,S.TenSV,M.TenMH,K.Diem
			FROM SinhVien AS S
				JOIN Ketqua AS K ON K.MaSV = S.MaSV
				JOIN MonHoc AS M ON M.MaMH = K.MaMH
		GROUP BY S.HoSV,S.TenSV,M.TenMH,K.Diem
		HAVING M.TenMH LIKE N'C? s? d? li?u'
		ORDER BY K.Diem DESC
-- CHO BI?T 3 SINH VIÊN CÓ ?I?M THI MÔN ?? HO?T TH?P NH?T G?M THÔNG TIN : HO TEN SV, TENKHOA,TENMON , ?I?M
	SELECT TOP(3) S.HoSV,S.TenSV,M.TenMH,K.Diem
			FROM SinhVien AS S
				JOIN Ketqua AS K ON K.MaSV = S.MaSV
				JOIN MonHoc AS M ON M.MaMH = K.MaMH
		GROUP BY S.HoSV,S.TenSV,M.TenMH,K.Diem
		HAVING M.TenMH LIKE N'?? h?a ?ng d?ng'
		ORDER BY K.Diem ASC

-- CHO BI?T KHOA NÀO CÓ SINH VIÊN N? NH?T G?M CÁC THÔNG TIN :MA KHOA,TENKHOA
	SELECT TOP (1) K.MaKH,K.TenKH, COUNT(S.MASV) AS [S? SINH VIÊN N?]
			FROM SinhVien AS S
				JOIN Khoa AS K ON K.MaKH=S.MaKH
			WHERE S.Phai='1'
		GROUP BY K.MaKH,K.TenKH	
		ORDER BY [S? SINH VIÊN N?] DESC
-- TH?NG KÊ SINH VIÊN THEO KHOA , G?M CÁC THÔNG TIN MAKHOA,TENKHOA T?NG S? SINH VIÊN , T?NG S? SINH VIÊN N?
	SELECT  K.MaKH,K.TenKH, COUNT(S.MASV)AS [TONG SV], COUNT(CASE WHEN S.PHAI = '1' THEN 1 END)  AS [S? SINH VIÊN N?]
			FROM SinhVien AS S
				JOIN Khoa AS K ON K.MaKH=S.MaKH
		GROUP BY K.MaKH,K.TenKH	
-- 


SELECT * FROM SinhVien
SELECT * FROM KHOA
SELECT * FROM Ketqua
SELECT * FROM MonHoc
	

